SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE url_record;
ALTER TABLE url_record AUTO_INCREMENT = 1;
TRUNCATE TABLE url_record_history;
ALTER TABLE url_record_history AUTO_INCREMENT = 1;
SET FOREIGN_KEY_CHECKS = 1;