name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: make resources directory
      run: mkdir ./_tracking/tracking/src/main/resources
    - name: make application.properties
      run: touch ./_tracking/tracking/src/main/resources/application.properties
    - name: get application.properties values
      run: echo "${{ secrets.APPLICATION }}" > ./_tracking/tracking/src/main/resources/application.properties

    - name: make test application.properties
      run: touch ./_tracking/tracking/src/test/resources/application.properties
    - name: get test application.properties values
      run: echo "${{ secrets.APPLICATION_TEST }}" > ./_tracking/tracking/src/test/resources/application.properties

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: 6
    
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'tracking_test'
        mysql root password: 'test'

    - name: Gradle Permission
      run: chmod +x ./_tracking/tracking/gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build
        build-root-directory: ./_tracking/tracking
